BashaBari/TBashaBari/Controllers/OwnerViewsBillController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TBashaBari.Data;
using TBashaBari.Models;
using System.Data.SqlClient;
using TBashaBari.Controllers;

namespace BashaBari.Controllers
{
    public class OwnerViewsBillController : Controller
    {
        List<BillInformation> _billinformationlist = new List<BillInformation>();
        List<TenantConnectsOwner> _tenantconnectsownerlist = new List<TenantConnectsOwner>();

        private readonly ApplicationDbContext _db;

        public OwnerViewsBillController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            FetchBillInfo();
            return View(_billinformationlist);
        }
        //:::::::::::::::::::::::::::::::::::::::::GET_Select
        public IActionResult Select()
        {
            FetchTenantConnectsOwner();
            return View(_tenantconnectsownerlist);
        }

        //:::::::::::::::::::::::::::::::::::::::::GET_BillExists
        public IActionResult BillExists()
        {
            FetchBillInfo();
            return View(_billinformationlist);
        }

        //:::::::::::::::::::::::::::::::::::::::::GET_CREATE
        public IActionResult Create(string TenantEmail)
        {
            ViewBag.SelectedTenantEmail = TenantEmail;
            return View();
        }
        //::::::::::::::::::::::::::::::::::::::::POST_CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(BillInformation obj)
        {
            if (ModelState.IsValid)
            {
                DatabaseConnection ob = new DatabaseConnection();
                if (ob.isBillInformationExist(obj.TenantEmail, obj.BillTime) == true) {
                    return RedirectToAction("BillExists");
                }
                _db.BillInformation.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //:::::::::::::::::::::::::::::::::::::::GET_EDIT
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var obj = _db.BillInformation.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }
        //::::::::::::::::::::::::::::::::::::::POST_EDIT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(BillInformation obj)
        {
            if (ModelState.IsValid)
            {
                _db.BillInformation.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //:::::::::::::::::::::::::::::::::::::::GET_Verify
        public IActionResult Verify(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var obj = _db.BillInformation.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }
        //::::::::::::::::::::::::::::::::::::::POST_Verify
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Verify(BillInformation obj)
        {
            if (ModelState.IsValid)
            {
                _db.BillInformation.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //:::::::::::::::::::::::::::::::::::::::GET_DELETE
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var obj = _db.BillInformation.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }
        //::::::::::::::::::::::::::::::::::::::POST_DELETE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(BillInformation obj)
        {
            if (ModelState.IsValid)
            {
                _db.BillInformation.Remove(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::://
        //:::::::::::::::::::::::::::::         custom methods        ::::::::::::::::::::::::::::::::://
        private void FetchBillInfo()
        {
            //User.Identity.Name returns current logged in user's email
            string queryString = "SELECT TOP 1000 [BillId],[OwnerEmail],[TenantEmail],[BillTime],[WaterAmount],[WaterPaid],[WaterVerified],[ElectricAmount]," +
                                        "[ElectricPaid],[ElectricVerified],[RentAmount],[RentPaid],[RentVerified],[GasAmount],[GasPaid],[GasVerified] " +
                                        "FROM [BashaBariWeb].[dbo].[BillInformation] " +
                                        "WHERE [OwnerEmail] = '" + User.Identity.Name + "' " +
                                        "ORDER BY [BillTime] DESC";
            //to clear the list initially
            if (_billinformationlist.Count > 0)
            {
                _billinformationlist.Clear();
            }

            //database operation
            DatabaseConnection obj = new DatabaseConnection();
            obj.DbConnect();
            while (obj.ExeQuery(queryString).Read())
            {
                _billinformationlist.Add(new BillInformation
                {
                    BillId = int.Parse(obj.ExeQuery(queryString)["BillId"].ToString()),
                    OwnerEmail = obj.ExeQuery(queryString)["OwnerEmail"].ToString(),
                    TenantEmail = obj.ExeQuery(queryString)["TenantEmail"].ToString(),
                    BillTime = obj.ExeQuery(queryString)["BillTime"].ToString(),
                    
                    WaterAmount = obj.ExeQuery(queryString)["WaterAmount"].ToString(),
                    WaterPaid = obj.ExeQuery(queryString)["WaterPaid"].ToString(),
                    WaterVerified = obj.ExeQuery(queryString)["WaterVerified"].ToString(),

                    ElectricAmount = obj.ExeQuery(queryString)["ElectricAmount"].ToString(),
                    ElectricPaid = obj.ExeQuery(queryString)["ElectricPaid"].ToString(),
                    ElectricVerified = obj.ExeQuery(queryString)["ElectricVerified"].ToString(),

                    RentAmount = obj.ExeQuery(queryString)["RentAmount"].ToString(),
                    RentPaid = obj.ExeQuery(queryString)["RentPaid"].ToString(),
                    RentVerified = obj.ExeQuery(queryString)["RentVerified"].ToString(),

                    GasAmount = obj.ExeQuery(queryString)["GasAmount"].ToString(),
                    GasPaid = obj.ExeQuery(queryString)["GasPaid"].ToString(),
                    GasVerified = obj.ExeQuery(queryString)["GasVerified"].ToString(),
                });
            }
            obj.CloseDbConnect();
        }

        private void FetchTenantConnectsOwner()
        {
            //User.Identity.Name returns current logged in user's email
            string queryString = "SELECT TOP 1000 [ConnectionId],[TenantEmail],[OwnerEmail],[IsConfirmed] " +
                                        "FROM [BashaBariWeb].[dbo].[TenantConnectsOwner] " +
                                        "WHERE [OwnerEmail] = '" + User.Identity.Name + "' " +
                                        "ORDER BY [ConnectionId] DESC";
            //to clear the list initially
            if (_tenantconnectsownerlist.Count > 0)
            {
                _tenantconnectsownerlist.Clear();
            }

            //database operation
            DatabaseConnection obj = new DatabaseConnection();
            obj.DbConnect();
            while (obj.ExeQuery(queryString).Read())
            {
                _tenantconnectsownerlist.Add(new TenantConnectsOwner
                {
                    ConnectionId = int.Parse(obj.ExeQuery(queryString)["ConnectionId"].ToString()),
                    TenantEmail = obj.ExeQuery(queryString)["TenantEmail"].ToString(),
                    OwnerEmail = obj.ExeQuery(queryString)["OwnerEmail"].ToString(),
                    IsConfirmed = obj.ExeQuery(queryString)["IsConfirmed"].ToString(),
                });
            }
            obj.CloseDbConnect();
        }


        //::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::://
    }
}

BashaBari/TBashaBari/Views/OwnerViewsBill/BillExists.cshtml
@using Microsoft.AspNetCore.Identity

<div class="border p-3 text-center">
    <div class="form-group">
        <h2 class="text-primary pl-3 font-weight-bold">This month's bill already exists for this User.</h2>
    </div>
    <a asp-action="Index" class="btn btn-primary w-20 m-2">
        Back
    </a>
</div>

BashaBari/TBashaBari/Views/OwnerViewsBill/Create.cshtml
@model TBashaBari.Models.BillInformation
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager



<form method="post" asp-action="Create" class="text-center">
    <div class="border p-3">
        <div class="form-group">
            <h2 class="text-primary font-weight-bold">Fill up the Bill Form</h2>
        </div>
        <input asp-for="OwnerEmail" class="form-control text-center py-4" value="@UserManager.GetUserName(User)" hidden />

        <label class="font-weight-bold pt-4">Tenant's Email:</label>
        <input asp-for="TenantEmail" class="form-control text-center py-4" value="@ViewBag.SelectedTenantEmail" readonly />

        <label class="font-weight-bold pt-4">Year & Month:</label>
        <input id="today" asp-for="BillTime" class="form-control text-center py-4" readonly />

        <label class="font-weight-bold pt-4">Water Bill Amount:</label>
        <input asp-for="WaterAmount" class="form-control text-center py-4" value="0.00" />
        <input asp-for="WaterPaid" class="form-control text-center py-4" value="No" hidden />
        <input asp-for="WaterVerified" class="form-control text-center py-4" value="No" hidden />
        <span asp-validation-for="WaterAmount" class="text-danger"></span>
        <br>

        <label class="font-weight-bold pt-4">Electric Bill Amount:</label>
        <input asp-for="ElectricAmount" class="form-control text-center py-4" value="0.00" />
        <input asp-for="ElectricPaid" class="form-control text-center py-4" value="No" hidden />
        <input asp-for="ElectricVerified" class="form-control text-center py-4" value="No" hidden />
        <span asp-validation-for="ElectricAmount" class="text-danger"></span>
        <br>

        <label class="font-weight-bold pt-4">Gas Bill Amount:</label>
        <input asp-for="GasAmount" class="form-control text-center py-4" value="0.00" />
        <input asp-for="GasPaid" class="form-control text-center py-4" value="No" hidden />
        <input asp-for="GasVerified" class="form-control text-center py-4" value="No" hidden />
        <span asp-validation-for="GasAmount" class="text-danger"></span>
        <br>

        <label class="font-weight-bold pt-4">Rent Amount:</label>
        <input asp-for="RentAmount" class="form-control text-center py-4" value="0.00" />
        <input asp-for="RentPaid" class="form-control text-center py-4" value="No" hidden />
        <input asp-for="RentVerified" class="form-control text-center py-4" value="No" hidden />
        <span asp-validation-for="RentAmount" class="text-danger"></span>
        <br>

        <br>
        <input type="submit" class="btn btn-success w-20 m-2" value="Post" />
        <a asp-action="Index" class="btn btn-primary w-20 m-2">
            Back
        </a>

    </div>
</form>

<script>
    var currentTime = new Date();
    var currentYear = currentTime.getFullYear();
    var currentMonth = currentTime.getMonth()+1;

    // Pad the currentMonth with leading zeros, if required
    currentMonth = (currentMonth < 10 ? "0" : "") + currentMonth;

    // Final Time
    document.querySelector("#today").value = currentYear + "-" + currentMonth;
</script>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

BashaBari/TBashaBari/Views/OwnerViewsBill/Delete.cshtml
@*@model TBashaBari.Models.OwnerNotice

<form method="post" class="text-center">
    <input asp-for="NoticeId" hidden />
    <div class="border p-3">
        <div class="form-group">
            <h2 class="text-primary pl-3 font-weight-bold">Are you sure, you want to delete the Notice?</h2>
        </div>
        <input asp-for="NoticeText" class="form-control" hidden />
        <input asp-for="NoticeTime" class="form-control" hidden />
        <input asp-for="OwnerEmail" class="form-control" hidden />
        <input type="submit" class="btn btn-danger w-20 m-2" value="Delete" />
        <a asp-action="Index" class="btn btn-primary w-20 m-2">
            Back
        </a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}*@

BashaBari/TBashaBari/Views/OwnerViewsBill/Edit.cshtml
@model TBashaBari.Models.BillInformation

<form method="post" class="text-center">
    <div class="border p-3">
        <div class="form-group">
            <h2 class="text-primary font-weight-bold">Edit Bill</h2>
        </div>

        <input asp-for="BillId" class="form-control text-center py-4" hidden />
        <input asp-for="OwnerEmail" class="form-control text-center py-4" hidden />
        
        <label class="font-weight-bold pt-4">Tenant's Email:</label>
        <input asp-for="TenantEmail" class="form-control text-center py-4" readonly />

        <label class="font-weight-bold pt-4">Year & Month:</label>
        <input id="today" asp-for="BillTime" class="form-control text-center py-4" readonly />

        <label class="font-weight-bold pt-4">Water Bill Amount:</label>
        <input asp-for="WaterAmount" class="form-control text-center py-4"/>
        <input asp-for="WaterPaid" class="form-control text-center py-4" hidden />
        <input asp-for="WaterVerified" class="form-control text-center py-4" hidden />
        <span asp-validation-for="WaterAmount" class="text-danger"></span>
        <br>

        <label class="font-weight-bold pt-4">Electric Bill Amount:</label>
        <input asp-for="ElectricAmount" class="form-control text-center py-4"/>
        <input asp-for="ElectricPaid" class="form-control text-center py-4" hidden />
        <input asp-for="ElectricVerified" class="form-control text-center py-4" hidden />
        <span asp-validation-for="ElectricAmount" class="text-danger"></span>
        <br>

        <label class="font-weight-bold pt-4">Gas Bill Amount:</label>
        <input asp-for="GasAmount" class="form-control text-center py-4"/>
        <input asp-for="GasPaid" class="form-control text-center py-4" hidden />
        <input asp-for="GasVerified" class="form-control text-center py-4" hidden />
        <span asp-validation-for="GasAmount" class="text-danger"></span>
        <br>

        <label class="font-weight-bold pt-4">Rent Amount:</label>
        <input asp-for="RentAmount" class="form-control text-center py-4" />
        <input asp-for="RentPaid" class="form-control text-center py-4" hidden />
        <input asp-for="RentVerified" class="form-control text-center py-4" hidden />
        <span asp-validation-for="RentAmount" class="text-danger"></span>

        <br>
        <input type="submit" class="btn btn-success w-20 m-2" value="Update" />
        <a asp-action="Index" class="btn btn-primary w-20 m-2">
            Back
        </a>

    </div>
</form>


@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

BashaBari/TBashaBari/Views/OwnerViewsBill/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using System.Data.SqlClient;
@using TBashaBari.Controllers;

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@{
    string GetUserFullName(string _Email)
    {
        //database operation to get user's fullname
        DatabaseConnection ob = new DatabaseConnection();
        string FullName = ob.getUserFullName(_Email);
        return FullName;
    }
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary font-weight-bold">Your Bill Information</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="OwnerViewsBill" asp-action="Select" class="btn btn-primary">
                Post New Bill
            </a>
        </div>
    </div>

    <br /><br />

    @{
        if (Model.Count != 0)
        {
            foreach (var obj in Model)
            {
                <div class="card w-80 mb-5 mx-5" style="background-color: gainsboro">
                    <div class="row no-gutters">
                        <div class="col-sm-2">
                            <div class="login-form-icon text-center">
                                <i class="fas fa-user-circle fa-6x text-secondary p-3"></i>
                            </div>
                        </div>
                        <div class="col-sm-10">
                                <div class="card-body">
                                    <div class="d-flex w-100 justify-content-between">
                                        <h5 class="font-weight-bold m-0 p-0">@GetUserFullName(obj.TenantEmail) </h5>
                                        <h5 class="font-weight-lighter m-0 p-0">@obj.BillTime</h5>
                                    </div>
                                    <small>[ @obj.TenantEmail ]</small>
                                    <br />
                                    <br />

                                    <table class="table table-sm">
                                        <thead>
                                            <tr>
                                                <th>Bill Type</th>
                                                <th>Amount</th>
                                                <th>Paid</th>
                                                <th>Verified</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>Water</td>
                                                <td>@obj.WaterAmount</td>
                                                <td>@obj.WaterPaid</td>
                                                <td>@obj.WaterVerified</td>
                                            </tr>
                                            <tr>
                                                <td>Electric</td>
                                                <td>@obj.ElectricAmount</td>
                                                <td>@obj.ElectricPaid</td>
                                                <td>@obj.ElectricVerified</td>
                                            </tr>
                                            <tr>
                                                <td>Gas</td>
                                                <td>@obj.GasAmount</td>
                                                <td>@obj.GasPaid</td>
                                                <td>@obj.GasVerified</td>
                                            </tr>
                                            <tr>
                                                <td>Rent</td>
                                                <td>@obj.RentAmount</td>
                                                <td>@obj.RentPaid</td>
                                                <td>@obj.RentVerified</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                    
                                    <div class="text-lg-right">
                                        <a asp-controller="OwnerViewsBill" asp-route-Id="@obj.BillId" asp-action="Edit" class="btn btn-primary ml-3">
                                            Edit
                                        </a>
                                        <a asp-controller="OwnerViewsBill" asp-route-Id="@obj.BillId" asp-action="Verify" class="btn btn-primary ml-3">
                                            Verify
                                        </a>
                                    </div>
                                </div>
                        </div>
                    </div>
                </div>
            }
        }
        else
        {
            <h5 class="p-4">You haven't posted any bill yet.</h5>
        }
    }
</div>

BashaBari/TBashaBari/Views/OwnerViewsBill/Select.cshtml
@using Microsoft.AspNetCore.Identity
@using System.Data.SqlClient;
@using TBashaBari.Controllers;

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@{
    string GetUserFullName(string _Email)
    {
        //database operation to get current tenants's fullname
        DatabaseConnection ob = new DatabaseConnection();
        string FullName = ob.getUserFullName(_Email);
        return FullName;
    }

}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary font-weight-bold">Select a Tenant</h2>
        </div>
    </div>
    <br /><br />

    @{
        if (Model.Count != 0)
        {
            foreach (var obj in Model)
            {
                if (obj.IsConfirmed == "Yes")
                {
                    <div class="card w-80 mb-5 mx-5" style="background-color: gainsboro">
                        <div class="row no-gutters">
                            <div class="col-sm-2">
                                <div class="login-form-icon text-center">
                                    <i class="fas fa-user-circle fa-6x text-secondary p-3"></i>
                                </div>
                            </div>
                            <div class="col-sm-10">
                                <div class="card-body">
                                    <div class="d-flex w-100 justify-content-between">
                                        <h5 class="font-weight-bold">@GetUserFullName(obj.TenantEmail) </h5>
                                    </div>
                                    <small>[ Email: @obj.TenantEmail ]</small>
                                    <p class="my-4 ml-2"></p>

                                    <div class="text-lg-right">
                                        <a asp-controller="OwnerViewsBill" asp-route-TenantEmail="@obj.TenantEmail" asp-action="Create" class="btn btn-danger mx-2">
                                            Select
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            }
        }
        else
        {
            <h5 class="px-4">You are not connected to any Tenants</h5>
        }
    }

</div>

BashaBari/TBashaBari/Views/OwnerViewsBill/Verify.cshtml
@model TBashaBari.Models.BillInformation

<form method="post" class="text-center">
    <div class="border p-3">
        <div class="form-group">
            <h2 class="text-primary font-weight-bold">Verify Bills</h2>
        </div>
        <input asp-for="BillId" class="form-control text-center py-4" hidden />
        <input asp-for="OwnerEmail" class="form-control text-center py-4" hidden />
        <input asp-for="TenantEmail" class="form-control text-center py-4" hidden />
        <input asp-for="BillTime" class="form-control text-center py-4" hidden />
        <input asp-for="WaterAmount" class="form-control text-center py-4" hidden />
        <input asp-for="WaterPaid" class="form-control text-center py-4" hidden />
        <input asp-for="ElectricAmount" class="form-control text-center py-4" hidden />
        <input asp-for="ElectricPaid" class="form-control text-center py-4" hidden />
        <input asp-for="GasAmount" class="form-control text-center py-4" hidden />
        <input asp-for="GasPaid" class="form-control text-center py-4" hidden />
        <input asp-for="RentAmount" class="form-control text-center py-4" hidden />
        <input asp-for="RentPaid" class="form-control text-center py-4" hidden />

        @if (Model.WaterVerified == "No" || Model.ElectricVerified == "No" || Model.GasVerified == "No" || Model.RentVerified == "No")
        {
            @if (Model.WaterVerified == "No" && Model.WaterPaid == "Yes")
            {
                <div class="d-flex justify-content-center">
                    <input type="checkbox" id="waterCheck" class="mt-1" onclick="waterFunction()">
                    <p class="font-weight-bold px-3">Water Bill</p>
                </div>
                <input id="water" asp-for="WaterVerified" class="form-control text-center py-4" hidden />
            }
            else
            {
                <input asp-for="WaterVerified" class="form-control text-center py-4" hidden />
            }

            @if (Model.ElectricVerified == "No" && Model.ElectricPaid == "Yes")
            {
                <div class="d-flex justify-content-center">
                    <input type="checkbox" id="electricCheck" class="mt-1" onclick="electricFunction()">
                    <p class="font-weight-bold px-3">Electric Bill</p>
                </div>
                <input id="electric" asp-for="ElectricVerified" class="form-control text-center py-4" hidden />
            }
            else
            {
                <input asp-for="ElectricVerified" class="form-control text-center py-4" hidden />
            }

            @if (Model.GasVerified == "No" && Model.GasPaid == "Yes")
            {
                <div class="d-flex justify-content-center">
                    <input type="checkbox" id="gasCheck" class="mt-1" onclick="gasFunction()">
                    <p class="font-weight-bold px-3">Gas Bill</p>
                </div>
                <input id="gas" asp-for="GasVerified" class="form-control text-center py-4" hidden />
            }
            else
            {
                <input asp-for="GasVerified" class="form-control text-center py-4" hidden />
            }


            @if (Model.RentVerified == "No" && Model.RentPaid == "Yes")
            {
                <div class="d-flex justify-content-center">
                    <input type="checkbox" id="rentCheck" class="mt-1" onclick="rentFunction()">
                    <p class="font-weight-bold px-3">Rent Bill</p>
                </div>
                <input id="rent" asp-for="RentVerified" class="form-control text-center py-4" hidden />
            }
            else
            {
                <input asp-for="RentVerified" class="form-control text-center py-4" hidden />
            }

            <br>
            <input type="submit" class="btn btn-success w-20 m-2" value="Confirm" />
        }
        else
        {
            <h5 class="p-4">All bills have been verified.</h5>
        }


        <a asp-action="Index" class="btn btn-primary w-20 m-2">
            Back
        </a>

    </div>
</form>

<script>
    function waterFunction() {
        // Get the checkbox
        var checkBox = document.getElementById("waterCheck");
        // Get the output text
        var text = document.getElementById("water");

        // If the checkbox is checked, display the output text
        if (checkBox.checked == true) {
            text.value = "Yes";
        } else {
            text.value = "No";
        }
    }

    function electricFunction() {
        // Get the checkbox
        var checkBox = document.getElementById("electricCheck");
        // Get the output text
        var text = document.getElementById("electric");

        // If the checkbox is checked, display the output text
        if (checkBox.checked == true) {
            text.value = "Yes";
        } else {
            text.value = "No";
        }
    }

    function gasFunction() {
        // Get the checkbox
        var checkBox = document.getElementById("gasCheck");
        // Get the output text
        var text = document.getElementById("gas");

        // If the checkbox is checked, display the output text
        if (checkBox.checked == true) {
            text.value = "Yes";
        } else {
            text.value = "No";
        }
    }

    function rentFunction() {
        // Get the checkbox
        var checkBox = document.getElementById("rentCheck");
        // Get the output text
        var text = document.getElementById("rent");

        // If the checkbox is checked, display the output text
        if (checkBox.checked == true) {
            text.value = "Yes";
        } else {
            text.value = "No";
        }
    }


</script>


@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}