BashaBari/TBashaBari/Models/TenantRequest.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TBashaBari.Models
{
    public class TenantRequest
    {
        [Key]
        public int RequestId { get; set; }

        [Required]
        [EmailAddress(ErrorMessage = "Email is not valid")]
        [DisplayName("Email")]
        public String TenantEmail { get; set; }

        [Required]
        [StringLength(100, MinimumLength = 1, ErrorMessage = "Maximum text length 100")]
        [DisplayName("Request")]
        public String RequestText { get; set; }

        [Required]
        [DisplayName("Time")]
        public String RequestTime { get; set; }

        [StringLength(100, MinimumLength = 1, ErrorMessage = "Maximum text length 100")]
        [DisplayName("Comment")]
        public String CommentOnRequestText { get; set; }

        [DisplayName("Time")]
        public String CommentOnRequestTime { get; set; }

    }
}

BashaBari/TBashaBari/Controllers/TenantRequestController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TBashaBari.Data;
using TBashaBari.Models;
using System.Data.SqlClient;
using TBashaBari.Controllers;

namespace BashaBari.Controllers
{
    public class TenantRequestController : Controller
    {
        List<TenantRequest> _tenantrequestlist = new List<TenantRequest>();

        private readonly ApplicationDbContext _db;

        public TenantRequestController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            FetchTenantRequest();
            return View(_tenantrequestlist);
        }

        //:::::::::::::::::::::::::::::::::::::::::GET_CREATE
        public IActionResult Create()
        {
            return View();
        }
        //::::::::::::::::::::::::::::::::::::::::POST_CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(TenantRequest obj)
        {
            if (ModelState.IsValid)
            {
                _db.TenantRequest.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
            
        }

        //:::::::::::::::::::::::::::::::::::::::GET_EDIT
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var obj = _db.TenantRequest.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }
        //::::::::::::::::::::::::::::::::::::::POST_EDIT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(TenantRequest obj)
        {
            if (ModelState.IsValid)
            {
                _db.TenantRequest.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //:::::::::::::::::::::::::::::::::::::::GET_DELETE
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var obj = _db.TenantRequest.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }
        //::::::::::::::::::::::::::::::::::::::POST_DELETE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(TenantRequest obj)
        {
            if (ModelState.IsValid)
            {
                _db.TenantRequest.Remove(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::://
        //:::::::::::::::::::::::::::::         custom methods        ::::::::::::::::::::::::::::::::://
        private void FetchTenantRequest()
        {
            //User.Identity.Name returns current logged in user's email
            string queryString = "SELECT TOP 1000 T.[RequestId],T.[TenantEmail],T.[RequestText],T.[RequestTime],T.[CommentOnRequestText],T.[CommentOnRequestTime],C.[TenantEmail],C.[IsConfirmed]" +
                                        "FROM [BashaBariWeb].[dbo].[TenantConnectsOwner] C JOIN [BashaBariWeb].[dbo].[TenantRequest] T " +
                                        "ON C.[TenantEmail] = T.[TenantEmail] " +
                                        "WHERE C.[IsConfirmed] = 'Yes' AND C.[TenantEmail] = '" + User.Identity.Name + "' " +
                                        "ORDER BY [RequestTime] DESC";
            //to clear the list initially
            if (_tenantrequestlist.Count > 0)
            {
                _tenantrequestlist.Clear();
            }

            //database operation
            DatabaseConnection obj = new DatabaseConnection();
            obj.DbConnect();
            while (obj.ExeQuery(queryString).Read())
            {
                _tenantrequestlist.Add(new TenantRequest
                {
                    RequestId = int.Parse(obj.ExeQuery(queryString)["RequestId"].ToString()),
                    TenantEmail = obj.ExeQuery(queryString)["TenantEmail"].ToString(),
                    RequestText = obj.ExeQuery(queryString)["RequestText"].ToString(),
                    RequestTime = obj.ExeQuery(queryString)["RequestTime"].ToString(),
                    CommentOnRequestText = obj.ExeQuery(queryString)["CommentOnRequestText"].ToString(),
                    CommentOnRequestTime = obj.ExeQuery(queryString)["CommentOnRequestTime"].ToString(),
                });
            }
            obj.CloseDbConnect();
        }


        //::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::://

    }
}

BashaBari/TBashaBari/Views/TenantRequest/Create.cshtml
@model TBashaBari.Models.TenantRequest
@using System.Data.SqlClient;
@using Microsoft.AspNetCore.Identity
@using TBashaBari.Controllers;

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@{
    bool isConnected(string _Email)
    {
        //database operation to get current tenants's fullname
        DatabaseConnection ob = new DatabaseConnection();
        bool booltemp = ob.isTenantConnected(_Email);
        return booltemp;
    }
}

<form method="post" asp-action="Create" class="text-center">
    @if (isConnected(UserManager.GetUserName(User)))
    {
        <div class="border p-3">
            <div class="form-group">
                <h2 class="text-primary font-weight-bold">Add a Request</h2>
            </div>
            <input id="today" asp-for="RequestTime" class="form-control" hidden />
            <input asp-for="TenantEmail" class="form-control" value="@UserManager.GetUserName(User)" hidden />
            <input asp-for="RequestText" class="form-control text-center py-4" />
            <br>
            <input type="submit" class="btn btn-success w-20 m-2" value="Post" />
            <a asp-action="Index" class="btn btn-primary w-20 m-2">
                Back
            </a>
        </div>
    }
    else
    {
        <div class="border p-3">
            <div class="form-group">
                <h2 class="text-primary font-weight-bold">You are not connected to any Owner</h2>
            </div>

            <a asp-action="Index" class="btn btn-primary w-20 m-2">
                Back
            </a>
        </div>
    }

</form>

<script>
    var today = new Date().toISOString().substr(0, 10);
    var currentTime = new Date();
    var currentHours = currentTime.getHours();
    var currentMinutes = currentTime.getMinutes();

    // Pad the currentMinutes with leading zeros, if required
    currentMinutes = (currentMinutes < 10 ? "0" : "") + currentMinutes;

    // Pad currentHours with leading zeros, if required
    currentHours = (currentHours < 10 ? "0" : "") + currentHours;

    // Compose the string for display
    var currentTimeString = currentHours + ":" + currentMinutes;

    // Final Time
    document.querySelector("#today").value = today + " at " + currentTimeString;
</script>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

BashaBari/TBashaBari/Views/TenantRequest/Delete.cshtml
@model TBashaBari.Models.TenantRequest

<form method="post" class="text-center">
    <input asp-for="RequestId" hidden />
    <div class="border p-3">
        <div class="form-group">
            <h2 class="text-primary font-weight-bold">Are you sure, you want to delete the Request?</h2>
        </div>
        <input asp-for="RequestText" class="form-control" hidden />
        <input asp-for="RequestTime" class="form-control" hidden />
        <input asp-for="TenantEmail" class="form-control" hidden />
        <input type="submit" class="btn btn-danger w-20 m-2" value="Delete" />
        <a asp-action="Index" class="btn btn-primary w-20 m-2">
            Back
        </a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

BashaBari/TBashaBari/Views/TenantRequest/Edit.cshtml
@model TBashaBari.Models.TenantRequest

<form method="post" class="text-center">
    <div class="border p-3">
        <div class="form-group">
            <h2 class="text-primary font-weight-bold">Edit Request</h2>
        </div>
        <input asp-for="RequestId" hidden />
        <input asp-for="CommentOnRequestText" hidden />
        <input asp-for="CommentOnRequestTime" hidden />
        <input id="today" asp-for="RequestTime" class="form-control" hidden />
        <input asp-for="TenantEmail" class="form-control" hidden />
        <input asp-for="RequestText" class="form-control text-center py-4" />
        <br>
        <input type="submit" class="btn btn-success w-20 m-2" value="Update" />
        <a asp-action="Index" class="btn btn-primary w-20 m-2">
            Back
        </a>
    </div>
</form>

<script>
    var today = new Date().toISOString().substr(0, 10);
    var currentTime = new Date();
    var currentHours = currentTime.getHours();
    var currentMinutes = currentTime.getMinutes();

    // Pad the currentMinutes with leading zeros, if required
    currentMinutes = (currentMinutes < 10 ? "0" : "") + currentMinutes;

    // Pad currentHours with leading zeros, if required
    currentHours = (currentHours < 10 ? "0" : "") + currentHours;

    // Compose the string for display
    var currentTimeString = currentHours + ":" + currentMinutes;

    // Final Time
    document.querySelector("#today").value = today + " at " + currentTimeString + "  [Edited]";
</script>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

BashaBari/TBashaBari/Views/TenantRequest/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using System.Data.SqlClient;
@using TBashaBari.Controllers;

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@{
    string GetUserFullName(string _Email)
    {
        //database operation to get current tenants's fullname
        DatabaseConnection ob = new DatabaseConnection();
        string FullName = ob.getUserFullName(_Email);
        return FullName;
    }
    string GetTenantsOwner(string _TenantEmail)
    {
        //database operation to get current tenants's fullname
        DatabaseConnection ob = new DatabaseConnection();
        string _OwnerEmail = ob.getTenantsOwner(_TenantEmail);
        return _OwnerEmail;
    }
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary font-weight-bold">Your Requests</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="TenantRequest" asp-action="Create" class="btn btn-primary">
                Post New Request
            </a>
        </div>
    </div>

    @{
        if (Model.Count != 0 && @GetTenantsOwner(UserManager.GetUserName(User)) != null)
        {
            foreach (var obj in Model)
            {
                <div class="card w-80 mt-5 mx-5" style="background-color: gainsboro">
                    <div class="row no-gutters">
                        <div class="col-sm-2">
                            <div class="login-form-icon text-center">
                                <i class="fas fa-user-circle fa-6x text-secondary p-3"></i>
                            </div>
                        </div>
                        <div class="col-sm-10">
                            <div class="card-body">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 class="font-weight-bold">@GetUserFullName(UserManager.GetUserName(User)) </h5>
                                    <small>@obj.RequestTime</small>
                                </div>
                                <small>[ @UserManager.GetUserName(User) ]</small>
                                <p class="my-4 ml-2">@obj.RequestText</p>
                                <div class="text-lg-right">
                                    <a asp-controller="TenantRequest" asp-route-Id="@obj.RequestId" asp-action="Edit" class="btn btn-primary mx-2">
                                        Edit
                                    </a>
                                    <a asp-controller="TenantRequest" asp-route-Id="@obj.RequestId" asp-action="Delete" class="btn btn-danger mx-2">
                                        Delete
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                @if (@obj.CommentOnRequestText != "")
                {
                    <div class="card w-80 mx-5 pl-5">
                        <div class="row flex-row-reverse no-gutters pl-5">
                            <div class="col-sm-11">
                                <div class="card-body flex-row-reverse text-right  mr-5">
                                    <div class="d-flex w-100 justify-content-between">
                                        <small>@obj.CommentOnRequestTime</small>
                                        <h5 class="font-weight-bold">@GetUserFullName(GetTenantsOwner(UserManager.GetUserName(User))) </h5>
                                    </div>
                                    <small>[ @GetTenantsOwner(UserManager.GetUserName(User)) ]</small>
                                    <p class="my-4 ml-2">@obj.CommentOnRequestText</p>
                                </div>
                            </div>

                        </div>
                    </div>
                }

            }
        }
        else if (Model.Count != 0 && @GetTenantsOwner(UserManager.GetUserName(User)) == null)
        {
            <h5 class="p-4">You are not connected to any owner.</h5>
        }
        else
        {
            <h5 class="p-4">You haven't posted any request yet.</h5>
        }
    }
</div>