BashaBari/TBashaBari/Models/OwnerNotice.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TBashaBari.Models
{
    public class OwnerNotice
    {
        [Key]
        public int NoticeId { get; set; }

        [Required]
        [EmailAddress(ErrorMessage = "Email is not valid")]
        [DisplayName("Email")]
        public String OwnerEmail { get; set; }

        [Required]
        [StringLength(100, MinimumLength = 1, ErrorMessage = "Maximum text length 100")]
        [DisplayName("Notice")]
        public String NoticeText { get; set; }

        [Required]
        [DisplayName("Time")]
        public String NoticeTime { get; set; }
        
    }
}

BashaBari/TBashaBari/Controllers/OwnerNoticeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TBashaBari.Data;
using TBashaBari.Models;
using System.Data.SqlClient;
using TBashaBari.Controllers;

namespace BashaBari.Controllers
{
    public class OwnerNoticeController : Controller
    {
        List<OwnerNotice> _ownernoticelist = new List<OwnerNotice>();

        private readonly ApplicationDbContext _db;

        public OwnerNoticeController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            FetchOwnerNotice();
            return View(_ownernoticelist);
        }

        //:::::::::::::::::::::::::::::::::::::::::GET_CREATE
        public IActionResult Create()
        {
            return View();
        }
        //::::::::::::::::::::::::::::::::::::::::POST_CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(OwnerNotice obj)
        {
            if (ModelState.IsValid)
            {
                _db.OwnerNotice.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //:::::::::::::::::::::::::::::::::::::::GET_EDIT
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var obj = _db.OwnerNotice.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }
        //::::::::::::::::::::::::::::::::::::::POST_EDIT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(OwnerNotice obj)
        {
            if (ModelState.IsValid)
            {
                _db.OwnerNotice.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //:::::::::::::::::::::::::::::::::::::::GET_DELETE
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var obj = _db.OwnerNotice.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }
        //::::::::::::::::::::::::::::::::::::::POST_DELETE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(OwnerNotice obj)
        {
            if (ModelState.IsValid)
            {
                _db.OwnerNotice.Remove(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::://
        //:::::::::::::::::::::::::::::         custom methods        ::::::::::::::::::::::::::::::::://
        private void FetchOwnerNotice()
        {
            //User.Identity.Name returns current logged in user's email
            string queryString = "SELECT TOP 1000 [NoticeId],[OwnerEmail],[NoticeText],[NoticeTime] " +
                                        "FROM [BashaBariWeb].[dbo].[OwnerNotice] " +
                                        "WHERE [OwnerEmail] = '" + User.Identity.Name + "' " +
                                        "ORDER BY [NoticeTime] DESC";
            //to clear the list initially
            if (_ownernoticelist.Count > 0)
            {
                _ownernoticelist.Clear();
            }

            //database operation
            DatabaseConnection obj = new DatabaseConnection();
            obj.DbConnect();
            while (obj.ExeQuery(queryString).Read())
            {
                _ownernoticelist.Add(new OwnerNotice
                {
                    NoticeId = int.Parse(obj.ExeQuery(queryString)["NoticeId"].ToString()),
                    OwnerEmail = obj.ExeQuery(queryString)["OwnerEmail"].ToString(),
                    NoticeText = obj.ExeQuery(queryString)["NoticeText"].ToString(),
                    NoticeTime = obj.ExeQuery(queryString)["NoticeTime"].ToString(),
                });
            }
            obj.CloseDbConnect();
        }


        //::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::://
    }
}

BashaBari/TBashaBari/Views/OwnerNotice/Create.cshtml
@model TBashaBari.Models.OwnerNotice
@using System.Data.SqlClient;
@using Microsoft.AspNetCore.Identity
@using TBashaBari.Controllers;

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@{
    bool isConnected(string _Email)
    {
        //database operation to get current tenants's fullname
        DatabaseConnection ob = new DatabaseConnection();
        bool booltemp = ob.isOwnerConnected(_Email);
        return booltemp;
    }
}

<form method="post" asp-action="Create" class="text-center">
    @if (isConnected(UserManager.GetUserName(User)))
    {
        <div class="border p-3">
            <div class="form-group">
                <h2 class="text-primary font-weight-bold">Add a Notice</h2>
            </div>
            <input id="today" asp-for="NoticeTime" class="form-control" hidden />
            <input asp-for="OwnerEmail" class="form-control" value="@UserManager.GetUserName(User)" hidden />
            <input asp-for="NoticeText" class="form-control text-center py-4" />
            <br>
            <input type="submit" class="btn btn-success w-20 m-2" value="Post" />
            <a asp-action="Index" class="btn btn-primary w-20 m-2">
                Back
            </a>

        </div>
    }
    else
    {
        <div class="border p-3">
            <div class="form-group">
                <h2 class="text-primary font-weight-bold">You are not connected to any Tenant</h2>
            </div>

            <a asp-action="Index" class="btn btn-primary w-20 m-2">
                Back
            </a>
        </div>
    }

</form>

<script>
    var today = new Date().toISOString().substr(0, 10);
    var currentTime = new Date();
    var currentHours = currentTime.getHours();
    var currentMinutes = currentTime.getMinutes();

    // Pad the currentMinutes with leading zeros, if required
    currentMinutes = (currentMinutes < 10 ? "0" : "") + currentMinutes;

    // Pad currentHours with leading zeros, if required
    currentHours = (currentHours < 10 ? "0" : "") + currentHours;

    // Compose the string for display
    var currentTimeString = currentHours + ":" + currentMinutes;

    // Final Time
    document.querySelector("#today").value = today + " at " + currentTimeString;
</script>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

BashaBari/TBashaBari/Views/OwnerNotice/Delete.cshtml
@model TBashaBari.Models.OwnerNotice

<form method="post" class="text-center">
    <input asp-for="NoticeId" hidden />
    <div class="border p-3">
        <div class="form-group">
            <h2 class="text-primary font-weight-bold">Are you sure, you want to delete the Notice?</h2>
        </div>
        <input asp-for="NoticeText" class="form-control" hidden />
        <input asp-for="NoticeTime" class="form-control" hidden />
        <input asp-for="OwnerEmail" class="form-control" hidden />
        <input type="submit" class="btn btn-danger w-20 m-2" value="Delete" />
        <a asp-action="Index" class="btn btn-primary w-20 m-2">
            Back
        </a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

BashaBari/TBashaBari/Views/OwnerNotice/Edit.cshtml
@model TBashaBari.Models.OwnerNotice

<form method="post" class="text-center">
    <div class="border p-3">
        <div class="form-group">
            <h2 class="text-primary font-weight-bold">Edit Notice</h2>
        </div>
        <input asp-for="NoticeId" hidden />
        <input id="today" asp-for="NoticeTime" class="form-control" hidden />
        <input asp-for="OwnerEmail" class="form-control" hidden />
        <input asp-for="NoticeText" class="form-control text-center py-4" />
        <br>
        <input type="submit" class="btn btn-success w-20 m-2" value="Update" />
        <a asp-action="Index" class="btn btn-primary w-20 m-2">
            Back
        </a>

    </div>
</form>

<script>
    var today = new Date().toISOString().substr(0, 10);
    var currentTime = new Date();
    var currentHours = currentTime.getHours();
    var currentMinutes = currentTime.getMinutes();

    // Pad the currentMinutes with leading zeros, if required
    currentMinutes = (currentMinutes < 10 ? "0" : "") + currentMinutes;

    // Pad currentHours with leading zeros, if required
    currentHours = (currentHours < 10 ? "0" : "") + currentHours;

    // Compose the string for display
    var currentTimeString = currentHours + ":" + currentMinutes;

    // Final Time
    document.querySelector("#today").value = today + " at " + currentTimeString + "  [Edited]";
</script>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

BashaBari/TBashaBari/Views/OwnerNotice/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using System.Data.SqlClient;
@using TBashaBari.Controllers;

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@{
    //database operation to get current user's fullname
    DatabaseConnection ob = new DatabaseConnection();
    string FullName = ob.getUserFullName(UserManager.GetUserName(User));
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary font-weight-bold">Your Notices</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="OwnerNotice" asp-action="Create" class="btn btn-primary">
                Post New Notice
            </a>
        </div>
    </div>

    <br /><br />

    @{
        if (Model.Count != 0)
        {
            foreach (var obj in Model)
            {
                <div class="card w-80 mb-5 mx-5" style="background-color: gainsboro">
                    <div class="row no-gutters">
                        <div class="col-sm-2">
                            <div class="login-form-icon text-center">
                                <i class="fas fa-user-circle fa-6x text-secondary p-3"></i>
                            </div>
                        </div>
                        <div class="col-sm-10">
                            <div class="card-body">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 class="font-weight-bold">@FullName </h5>
                                    <small>@obj.NoticeTime</small>
                                </div>
                                <small>[ @obj.OwnerEmail ]</small>
                                <p class="my-4 ml-2">@obj.NoticeText</p>
                                <div class="text-lg-right">
                                    <a asp-controller="OwnerNotice" asp-route-Id="@obj.NoticeId" asp-action="Edit" class="btn btn-primary ml-3">
                                        Edit
                                    </a>
                                    <a asp-controller="OwnerNotice" asp-route-Id="@obj.NoticeId" asp-action="Delete" class="btn btn-primary ml-3">
                                        Delete
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        }
        else
        {
            <h5 class="p-4">You haven't posted any notice yet.</h5>
        }
    }
</div>