BashaBari/TBashaBari/Controllers/OwnerViewsConnectedListController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TBashaBari.Controllers;
using TBashaBari.Data;
using TBashaBari.Models;

namespace BashaBari.Controllers
{
    public class OwnerViewsConnectedListController : Controller
    {
        List<TenantConnectsOwner> _tenantconnectsownerlist = new List<TenantConnectsOwner>();
        private readonly ApplicationDbContext _db;

        public OwnerViewsConnectedListController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            FetchTenantConnectsOwner();
            return View(_tenantconnectsownerlist);
        }

        //GET
        public IActionResult Create()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(TenantConnectsOwner obj)
        {
            if (ModelState.IsValid)
            {
                _db.TenantConnectsOwner.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
            
        }

        //GET_EDIT
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var obj = _db.TenantConnectsOwner.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        //POST_EDIT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(TenantConnectsOwner obj)
        {
            if (ModelState.IsValid)
            {
                _db.TenantConnectsOwner.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //GET_DELETE
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var obj = _db.TenantConnectsOwner.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        //POST_DELETE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(TenantConnectsOwner obj)
        {
            if (ModelState.IsValid)
            {
                _db.TenantConnectsOwner.Remove(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::://
        //:::::::::::::::::::::::::::::         custom methods        ::::::::::::::::::::::::::::::::://
        private void FetchTenantConnectsOwner()
        {
            //User.Identity.Name returns current logged in user's email
            string queryString = "SELECT TOP 1000 [ConnectionId],[TenantEmail],[OwnerEmail],[IsConfirmed] " +
                                        "FROM [BashaBariWeb].[dbo].[TenantConnectsOwner] " +
                                        "WHERE [OwnerEmail] = '" + User.Identity.Name + "' " +
                                        "ORDER BY [ConnectionId] DESC";
            //to clear the list initially
            if (_tenantconnectsownerlist.Count > 0)
            {
                _tenantconnectsownerlist.Clear();
            }

            //database operation
            DatabaseConnection obj = new DatabaseConnection();
            obj.DbConnect();
            while (obj.ExeQuery(queryString).Read())
            {
                _tenantconnectsownerlist.Add(new TenantConnectsOwner
                {
                    ConnectionId = int.Parse(obj.ExeQuery(queryString)["ConnectionId"].ToString()),
                    TenantEmail = obj.ExeQuery(queryString)["TenantEmail"].ToString(),
                    OwnerEmail = obj.ExeQuery(queryString)["OwnerEmail"].ToString(),
                    IsConfirmed = obj.ExeQuery(queryString)["IsConfirmed"].ToString(),
                });
            }
            obj.CloseDbConnect();
        }


        //::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::://

    }
}

BashaBari/TBashaBari/Views/OwnerViewsConnectedList/Create.cshtml
<!--model TBashaBari.Models.TenantConnectsOwner
using Microsoft.AspNetCore.Identity

nject SignInManager<IdentityUser> SignInManagerinject UserManager<IdentityUser> UserManager

<form method="post" asp-action="Create">
    <div class="border p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-3">Add Your Tenant</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="TenantEmail"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="TenantEmail" class="form-control" value="UserManager.GetUserName(User)" readonly />
                        <span asp-validation-for="TenantEmail" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="OwnerEmail"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="OwnerEmail" class="form-control" />
                        <span asp-validation-for="OwnerEmail" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="IsConfirmed"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="IsConfirmed" class="form-control" value="No" readonly/>
                        <span asp-validation-for="IsConfirmed" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Create" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100">
                                Back
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">-->
                @* Keep this empty *@
            <!--</div>
        </div>
    </div>
</form>

<script>
    let today = new Date().toISOString().substr(0, 10);
    document.querySelector("#today").value = today;
</script>

section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}-->

BashaBari/TBashaBari/Views/OwnerViewsConnectedList/Delete.cshtml
@model TBashaBari.Models.TenantConnectsOwner

<form method="post" class="text-center">
    <input asp-for="ConnectionId" hidden />
    <div class="border p-3">
        <div class="form-group">
            <h2 class="text-primary font-weight-bold">Are you sure, you want to delete this Tenant?</h2>
        </div>
        <input asp-for="TenantEmail" class="form-control" readonly hidden />
        <input asp-for="OwnerEmail" class="form-control" readonly hidden />
        <input asp-for="IsConfirmed" class="form-control" readonly hidden />
        <input type="submit" class="btn btn-danger w-20 m-2" value="Delete" />
        <a asp-action="Index" class="btn btn-primary w-20 m-2">
            Back
        </a>
    </div>
</form>


@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

BashaBari/TBashaBari/Views/OwnerViewsConnectedList/Edit.cshtml
@model TBashaBari.Models.TenantConnectsOwner

<form method="post" class="text-center">
    <input asp-for="ConnectionId" hidden />
    <div class="border p-3">
        <div class="form-group">
            <h2 class="text-primary font-weight-bold">Do you want to add this Tenant?</h2>
        </div>
        <input asp-for="TenantEmail" class="form-control" readonly hidden />
        <input asp-for="OwnerEmail" class="form-control" readonly hidden />
        <input asp-for="IsConfirmed" class="form-control" value="Yes" hidden />
        <input type="submit" class="btn btn-danger w-20 m-2" value="Confirm" />
        <a asp-action="Index" class="btn btn-primary w-20 m-2">
            Back
        </a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

BashaBari/TBashaBari/Views/OwnerViewsConnectedList/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using System.Data.SqlClient;
@using TBashaBari.Controllers;

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@{
    string GetUserFullName(string _Email)
    {
        //database operation to get current tenants's fullname
        DatabaseConnection ob = new DatabaseConnection();
        string FullName = ob.getUserFullName(_Email);
        return FullName;
    }
    string GetUserPhoneNumber(string _Email)
    {
        //database operation to get current tenants's fullname
        DatabaseConnection ob = new DatabaseConnection();
        string PhoneNumber = ob.getUserPhoneNumber(_Email);
        return PhoneNumber;
    }

}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary font-weight-bold">Your Tenant's List</h2>
        </div>
    </div>
    <br /><br />

    @{
        if (Model.Count != 0)
        {
            foreach (var obj in Model)
            {
                <div class="card w-80 mb-5 mx-5" style="background-color: gainsboro">
                    <div class="row no-gutters">
                        <div class="col-sm-2">
                            <div class="login-form-icon text-center">
                                <i class="fas fa-user-circle fa-6x text-secondary p-3"></i>
                            </div>
                        </div>
                        <div class="col-sm-10">
                                <div class="card-body">
                                    <div class="d-flex w-100 justify-content-between">
                                        @{if (obj.IsConfirmed == "No")
                                            {
                                                <h5 class="font-weight-bold">[Pending] @GetUserFullName(obj.TenantEmail) </h5>
                                            }
                                            else
                                            {
                                                <h5 class="font-weight-bold">@GetUserFullName(obj.TenantEmail) </h5>

                                            }
                                        }
                                    </div>
                                    <small>[ Email: @obj.TenantEmail ]</small>
                                    <br />
                                    <small>[ Phone: @GetUserPhoneNumber(obj.TenantEmail) ]</small>
                                    <p class="my-4 ml-2"></p>

                                    <div class="text-lg-right">
                                        @{if (obj.IsConfirmed == "No")
                                            {
                                                <a asp-controller="OwnerViewsConnectedList" asp-route-Id="@obj.ConnectionId" asp-action="Edit" class="btn btn-primary mx-2">
                                                    Accept
                                                </a>
                                            }
                                        }
                                        <a asp-controller="OwnerViewsConnectedList" asp-route-Id="@obj.ConnectionId" asp-action="Delete" class="btn btn-danger mx-2">
                                            Remove
                                        </a>
                                    </div>

                                </div>
                        </div>
                    </div>
                </div>
            }
        }
        else
        {
            <h5 class="px-4">You are not connected to any Tenants</h5>
        }
    }

</div>